name: scrcpy
title: scrcpy [unofficial]

adopt-info: scrcpy

summary: Display and control your Android device

description: |
  This application provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access.  It works on GNU/Linux, Windows and MacOS.
  This is an unofficial snap. The code of scrcpy can be found at: https://github.com/Genymobile/scrcpy
   
license: Apache-2.0
grade: stable 
confinement: strict 

base: core18

architectures:
- build-on: i386
- build-on: amd64

apps:
  scrcpy:
    command: usr/local/bin/scrcpy
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/android"
  adb:  
    command: usr/bin/adb
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/android/"

layout:
  /usr/local/share/scrcpy:
    bind: $SNAP/usr/local/share/scrcpy

parts:
  scrcpy-server:
    plugin: nil
    override-pull:
      wget https://github.com/Genymobile/scrcpy/releases/download/v1.8/scrcpy-server-v1.8.jar
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/local/share/scrcpy/
      cp scrcpy-server-v1.8.jar $SNAPCRAFT_PART_INSTALL/usr/local/share/scrcpy/scrcpy-server.jar

  scrcpy:
    source: https://github.com/Genymobile/scrcpy.git
    plugin: meson
    meson-parameters: 
      - --buildtype=release
      - --strip 
      - -Db_lto=true
      - -Dbuild_server=false
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version $(git describe --tag)      
    build-packages:
      - make
      - gcc
      - pkg-config
      - meson
      - ninja-build
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libsdl2-dev
      - wget
    stage-packages:
      - ffmpeg
      - libsdl2-2.0-0
      - libslang2
      - libglu1-mesa
      - adb

plugs:
# For snaps with a graphical user interface:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:
# Graphics rendering
  opengl:
# Audio
  pulseaudio:
# Network access may be required for connection over TCP/IP
  network:
# adb support
  adb-support:
